#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18051
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Drench.Resource", IsApplication=true)]

namespace Drench
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050021
			public const int aboutZyanButton = 2131034145;
			
			// aapt resource value: 0x7f050007
			public const int boardTable = 2131034119;
			
			// aapt resource value: 0x7f050010
			public const int button0 = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int button1 = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int button2 = 2131034130;
			
			// aapt resource value: 0x7f050014
			public const int button3 = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int button4 = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int button5 = 2131034134;
			
			// aapt resource value: 0x7f05000e
			public const int buttonsTable = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int cancelButton = 2131034125;
			
			// aapt resource value: 0x7f05002c
			public const int dumbButton = 2131034156;
			
			// aapt resource value: 0x7f05002e
			public const int expertButton = 2131034158;
			
			// aapt resource value: 0x7f050002
			public const int joinGameButton = 2131034114;
			
			// aapt resource value: 0x7f05001f
			public const int joinNetworkGameButton = 2131034143;
			
			// aapt resource value: 0x7f050027
			public const int limit20button = 2131034151;
			
			// aapt resource value: 0x7f050028
			public const int limit30button = 2131034152;
			
			// aapt resource value: 0x7f050029
			public const int limit40button = 2131034153;
			
			// aapt resource value: 0x7f050019
			public const int mainLinearLayout = 2131034137;
			
			// aapt resource value: 0x7f050009
			public const int messageTable = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int messageView = 2131034122;
			
			// aapt resource value: 0x7f05002d
			public const int normButton = 2131034157;
			
			// aapt resource value: 0x7f05000c
			public const int playAgainButton = 2131034124;
			
			// aapt resource value: 0x7f050024
			public const int progressBar1 = 2131034148;
			
			// aapt resource value: 0x7f050026
			public const int radioGroup1 = 2131034150;
			
			// aapt resource value: 0x7f05002b
			public const int radioGroup2 = 2131034155;
			
			// aapt resource value: 0x7f050006
			public const int rootLayout = 2131034118;
			
			// aapt resource value: 0x7f050031
			public const int saveSettingsButton = 2131034161;
			
			// aapt resource value: 0x7f050023
			public const int serverAddressTextView = 2131034147;
			
			// aapt resource value: 0x7f050001
			public const int serverAddressView = 2131034113;
			
			// aapt resource value: 0x7f050020
			public const int settingsButton = 2131034144;
			
			// aapt resource value: 0x7f05001b
			public const int singlePlayerGameButton = 2131034139;
			
			// aapt resource value: 0x7f05001d
			public const int startNetworkGameButton = 2131034141;
			
			// aapt resource value: 0x7f05002f
			public const int symmetricCheck = 2131034159;
			
			// aapt resource value: 0x7f050008
			public const int tableRow1 = 2131034120;
			
			// aapt resource value: 0x7f05000b
			public const int tableRow11 = 2131034123;
			
			// aapt resource value: 0x7f050017
			public const int tableRow12 = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int tableRow2 = 2131034136;
			
			// aapt resource value: 0x7f050013
			public const int tableRow3 = 2131034131;
			
			// aapt resource value: 0x7f05000f
			public const int tableRow4 = 2131034127;
			
			// aapt resource value: 0x7f05001c
			public const int tableRow5 = 2131034140;
			
			// aapt resource value: 0x7f05001e
			public const int tableRow6 = 2131034142;
			
			// aapt resource value: 0x7f050022
			public const int textView1 = 2131034146;
			
			// aapt resource value: 0x7f05002a
			public const int textView2 = 2131034154;
			
			// aapt resource value: 0x7f050003
			public const int titleLayout = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int titleLeft = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int titleRight = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int topMessageView = 2131034112;
			
			// aapt resource value: 0x7f05001a
			public const int twoPlayersGameButton = 2131034138;
			
			// aapt resource value: 0x7f050032
			public const int useDefaultSettingsButton = 2131034162;
			
			// aapt resource value: 0x7f050030
			public const int vibrateCheck = 2131034160;
			
			// aapt resource value: 0x7f050025
			public const int waitingTextView = 2131034149;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ConnectForm = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CustomTitle = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DrenchBoard = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ServerStarted = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Settings = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
